### ISSUE TITLE
参数改为传进来的 appname 而不是自定义的 filename

### ISSUE THREAD

**Issue by zezhou** [larkjs/lark-bootstrap#9]

**Comment by viRingbells** [comment]
Done，现在支持命令行（优先）和配置来设置app的名称：
命令行：
node app.js --lark-name='This is the name of the app'
配置：
config.processManage.name = 'This is the name of the app'
bootstrap(app, config);
需要注意的是，启停必须用相同的name。因此需要避免修改名称后直接用--lark-restart重启。
